rsvim_core/src/ui/widget/window/viewport.rs
rsvim_core/src/ui/widget/window/viewport/sync.rs

This adds a more detailed index mapping in viewport, from each unicode char index to its start/end display columns.
It would help a lot when we implement the cursor movement on a viewport (in following work), because the cursor movement needs to know its adjacent char's position on both unicode char index and terminal displayed cells.
In previous work, the viewport only contains the start/end char index and start/end display column on each row in the window, but not the detailed each unicode chars inside the row.

feat(ui): maps every char index to its display boundary columns in viewport

---

Cargo.toml
rsvim_core/src/buf.rs
rsvim_core/src/ui/widget/window/content.rs
rsvim_core/src/ui/widget/window/viewport.rs
rsvim_core/src/ui/widget/window/viewport/sync.rs
rust-toolchain.toml

This PR re-implements (rewritten) text rendering in TUI window with `line-break` option is on, which has been disabled in previous #253 .

feat(win): impl line-break/word-wrap rendering (again)

---

.github/workflows/ci.yml
rsvim_core/src/buf/opt.rs
rsvim_core/src/defaults/buf.rs
rsvim_core/src/defaults/win.rs
rsvim_core/src/state/fsm/normal.rs
rsvim_core/src/ui/widget/window/opt.rs

This PR fixes the edge case: when cursor moving vertically from the end position of a longer line to shorter line, the cursor will have to re-locate its position to the end of the shorter line (because the shorter line has less chars and doesn't have the same char position compared with the longer line).

fix(cursor): fix cursor position at eol when move vertically

---

.github/workflows/ci.yml
.github/workflows/nightly_miri.yml
Cargo.toml
README.md
dev.py
rsvim_core/Cargo.toml

Actually when running `cargo miri` again, the memory safety issue already disappears (mentioned in https://github.com/cessen/ropey/issues/103). Guess it is been fixed in my previous refactor PRs.
This PR also adjusts some workflows, avoid running `cargo miri` on every PRs and pushes because it uses too much time of github actions. Instead I will run `cargo miri` nightly.

fix(miri): fix potential memory safety issue previously detected by cargo miri

---

dev.py
rsvim_core/src/buf/cidx.rs
rsvim_core/src/envar/path_config.rs
rsvim_core/src/js.rs
rsvim_core/src/ui/canvas/frame/cell.rs
rsvim_core/src/ui/tree.rs
rsvim_core/src/ui/widget/window.rs
rsvim_core/src/ui/widget/window/viewport.rs
rsvim_core/src/ui/widget/window/viewport/sync.rs

When cursor moves up/down, there are two cases:
1. If the target cursor position is still inside current window, then we simply change the cursor position in the window, which is easy.
2. If the target cursor position is outside of current window (since buffer/file contents can be much bigger than a window and not fully show in the window), then we need to first scroll the buffer to show the target line/char, then update the cursor position.
This PR (and previous #365) helps calculate the new viewport anchor (`start_line`/`start_column`) when scrolling buffer up/down. Also fixes several issues in previous PR.

feat(cursor): add search viewport anchor upward api

---

rsvim_core/src/ui/widget/window/viewport.rs
rsvim_core/src/ui/widget/window/viewport/sync.rs

After several days of struggling with the anchor search algorithm for 0-width empty eol (end-of-line), I found current implementations has seriously confused 3 scenarios for `wrap=true`:
1. The viewport (window) cannot fully contain the cursor line (the line where cursor is at), i.e. the line is too long and have to be truncated to be put.
2. The viewport can contain the cursor line, i.e. the line is not too long. And further we can split this into more sub cases:
1. The viewport exactly/only contains the cursor line. And we have a specific edge case when considering the empty eol:
1. The last visible (non 0-width) char of cursor line is at the bottom-right corner of the viewport, and thus the empty eol is actually out of viewport. (If in insert mode, we need to move viewport to right …

fix(viewport): refactor wrap line anchor searching algorithms and fixes edge cases

---

rsvim_core/src/state/fsm/insert.rs
rsvim_core/src/state/fsm/normal.rs
rsvim_core/src/state/ops/cursor_ops.rs

Includes the empty eol (end-of-line) when calculating cursor positions when it moves in insert mode. It also fixes some test cases/bugs in normal mode, which should be introduced in previous work #424 .

feat(cursor): include empty eol when calculate cursor positions for insert mode

---

rsvim_core/src/buf/opt.rs
rsvim_core/src/buf/opt/file_format.rs
rsvim_core/src/defaults/ascii.rs
rsvim_core/src/defaults/ascii/end_of_line.rs
rsvim_core/src/defaults/buf.rs
rsvim_core/src/state/fsm/insert.rs
rsvim_core/src/test/buf.rs

This PR inserts an an extra eol char at the file end (only when the file doesn't have it), also adds the [fileformat](https://vimhelp.org/options.txt.html#%27fileformat%27) option. The 'fileformat' option is still internal, not exposed to js script yet.

feat(insert): insert eol when file has no eol at end

---

rsvim_core/src/evloop.rs
rsvim_core/src/js.rs
rsvim_core/src/ui/tree.rs
rsvim_core/src/ui/widget/cmdline.rs

TODO: As rsvim add more and more UI widgets, it eventually needs a **layout** framework to provide the ability to help manage all the widgets inside the _screen_ (i.e. the whole terminal).

feat(cmdline): initialize default cmdline widget

---

rsvim_core/src/ui/canvas.rs
rsvim_core/src/ui/canvas_tests.rs
rsvim_core/src/ui/viewport/draw.rs

Fix #534 
Fixes the canvas system by filling the following logic cells with empty string (`""`), when a char displays width > 1. The leading logic cell will store the character itself, while following ones will store empty strings and fill the canvas.
At the beginning, I was simply thinking a terminal is a logic `M * N` cells, each logic cell display a 1-width char in the terminal. But then I noticed, there are multiple kinds of ASCII/unicode characters with various length displayed on the terminal (or say, use different cells in the terminal). This PR fixes this issue.

fix(unicode): fix logic cells canvas drawing for >1 width unicode characters

---

rsvim_core/src/js.rs
rsvim_core/src/js/module.rs
rsvim_core/src/js/module/module_map.rs
rsvim_core/src/test.rs

This PR adds the old "without snapshot" version constructor back to js runtime.
In previous work #199 , "v8 snapshot" is firstly successful built for the builtin modules (i.e. the `Rsvim` global objects), then in following work #202 and #205 , the "from scratch" version constructor is been replaced with "v8 snapshot" constructor. This is mostly for performance reason, it greatly speed up the `rsvim` cli startup.
But now we want to add unit tests for "js" modules to improve code quality, and need to make js runtime mock for each testing cases. Thus bring the "from scratch" constructor back to js runtime.

refactor(js): add old "from scratch" constructor back to js runtime

---

rsvim_core/src/buf/text.rs
rsvim_core/src/js.rs

For the 'Text' structure, its inside lines display width cache field 'cached_lines_width' doesn't have to be 'Rc<RefCell<>>', just 'RefCell' works as well.

refactor(buf): drop unnecessary 'Rc' pointer inside text cache

---

rsvim_core/src/cli.rs
rsvim_core/src/cli_tests.rs
rsvim_core/src/js.rs
rsvim_core/src/js/loader/fs_loader.rs
rsvim_core/src/js/module.rs
rsvim_core/src/js/module/module_map.rs
rsvim_core/src/js/module_tests.rs
rsvim_core/src/lib.rs
rsvim_core/src/log.rs
rsvim_core/src/test.rs
rsvim_core/src/test/js.rs

This PR completes several tasks:
1. Split test cases from `crate::cli`
2. Fix `FsModuleLoader` detection when module specifier has no extension
3. Add test cases for fetching modules and fs loaders
TODO: fix #555

fix(loader): fix module fs loader and add tests for "fetch_module_tree"

---

rsvim_core/src/js.rs
rsvim_core/src/js/runtime/00__web.ts

Skips the timeout callback execution if a timer is been cancelled before its delay comes.

fix(timeout): skip 'setTimeout' callback execution if cancelled

---

rsvim_core/src/state/fsm/command_line_ex.rs
rsvim_core/src/state/fsm/command_line_ex_tests.rs
rsvim_core/src/state/fsm/insert.rs
rsvim_core/src/state/fsm/insert_tests.rs
rsvim_core/src/state/fsm/normal_tests.rs
rsvim_core/src/state/ops.rs

This PR refactors the "Operation::CursorInsert(CompactString)" enum for insert mode, the internal data structure is changed to:
```rust
enum Operation {
CursorInsert(CursorInsertPayload),
// ...
}
enum CursorInsertPayload {
Text(CompactString),
Tab,
Eol
}
```
This is mostly because some chars (like eol, tab) can be evaluate into different actual chars based on different editor options. For example:
- With default tab option, "Tab" key will insert '\t'. With "expandtab" option (it is not implemented yet, but will be implemented eventually), it will insert N spaces.
- On unix system, "Eol" will insert '\n', on Windows, it will insert "\r\n".
"Operation" hides these low level details, and provide a more user friendly api.

fix(insert): refactor "CursorInsert" op and insert tab

---

rsvim_core/src/state/fsm/normal.rs
rsvim_core/src/state/ops/cursor_ops.rs
rsvim_core/src/ui/viewport.rs
rsvim_core/src/ui/widget.rs
rsvim_core/src/ui/widget/command_line.rs
rsvim_core/src/ui/widget/window.rs

This PR refactors the viewport calculation by:
1. Create new "EditableWidgetable" trait, which contains all the necessary methods for an editable widget (i.e. Window and Command-line Input)
2. Wrap "Window" and "Command-line Input" widgets with this new trait
3. Drop duplicated code logic in `cursor_ops` module, replace them with new `&mut dyn EditableWidgetable` type.

refactor(viewport): create new "EditableWidgetable" trait to drop duplicated matchings

---

rsvim_core/src/ui/canvas.rs

For windows terminal, current shaders are flushing without hiding the cursor, this causes the cursor twinkling/jumping on the TUI screen (I can see it with my eyes, but here I didn't provide any screen recordings). This PR will first hide the cursors, then flush the shaders, finally restore (show) the cursor back.
This issue seems never happens on mac/linux, but still I apply the logic to all OS (just simplify the code logic).

fix(canvas): avoid cursor twinkling while flushing canvas shaders for windows terminal

---

rsvim_core/src/js.rs
rsvim_core/src/js/hook.rs
rsvim_core/src/js/loader/fs_loader.rs
rsvim_core/src/js/module/es_module.rs
rsvim_core/src/js/pending.rs

This PR is a follow up of #631 , it avoids some duplicated event loop ticks in dynamic import stage. In previous implementation, it always requires another tick if "module_map.pending" is not empty. In this PR, it only requires tick when "module_map.pending.len() > pending_imports.len()". Because the "async loader" is handled by tokio runtime, and it actually doesn't need an event loop tick to run.
BTW, #651 is also a follow up of #631 , it rewrites the "JsFuture" and messages between tokio runtime and js runtime event loop, to make the code base cleaner.

perf(js): avoid duplicate loop tick when waiting for dynamic import loaders

---

rsvim_core/src/js/binding.rs
rsvim_core/src/js/binding/global_rsvim/cmd.rs
rsvim_core/src/js/binding/global_rsvim/cmd_tests.rs
rsvim_core/src/js/binding/global_this/timeout_tests.rs
rsvim_core/src/js/runtime/01__rsvim.d.ts
rsvim_core/src/js/runtime/01__rsvim.js
rsvim_core/src/js/runtime/01__rsvim.ts
rsvim_core/src/tests/evloop.rs

Close #701 
- Refactors `Rsvim.cmd.list`, it now returns command names instead of full definitions.
- Add `Rsvim.cmd.get`, it gets a full definition by its name.

refactor(cmd): refactor `Rsvim.cmd.list` and add `Rsvim.cmd.get`

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

GitHub has deprecated macos-13, the "macos-14-large" becomes the only machine with Intel x64 chip, which is not available for free plan. Have to drop support on this.

ci(mac): drop macos-13 and intel x64 chip support

---

rsvim_core/Cargo.toml
rsvim_core/src/buf/opt.rs
rsvim_core/src/js/binding/global_rsvim/opt.rs
rsvim_core/src/ui/widget/command_line.rs
rsvim_core/src/ui/widget/window/opt.rs

Close #700 
Use smaller data types to reduce memory usage, i.e. use `u8` instead of `u16`.

perf(opts): reduce internal options data types

---

rsvim_core/src/buf/opt.rs
rsvim_core/src/js/command/attr.rs
rsvim_core/src/js/command/opt.rs
rsvim_core/src/ui/widget/window/opt.rs
rsvim_core/src/util/flag.rs

refactor(opts): use paste! lower/upper/camel to reduce duplicated macro arguments
